import Head from 'next/head';
import styles from '@styles/Home.module.css';

import Main from '@components/main';

export default function Home() {
    return (
        <div className={styles.container}>
            <Head>
                <title>스터디 그룹 통장</title>
                <meta name="description" content="Generated by create next app"/>
            </Head>

            <Main />
        </div>
    )
}